export const GROUP_CAPSULE = 29;

export const GROUP_T1_FRIGATE = 25;
export const GROUP_ASSAULT_FRIGATE = 324;
export const GROUP_INTERCEPTOR = 831;
export const GROUP_COVERT_OPS = 830;
export const GROUP_STEALTH_BOMBER = 834;
export const GROUP_ELECTRONIC_ATTACK_SHIP = 893;
export const GROUP_LOGISTICS_FRIGATE = 1527;

export const GROUP_T1_DESTROYER = 420;
export const GROUP_INTERDICTOR = 541;
export const GROUP_COMMAND_DESTROYER = 1534;
export const GROUP_TACTICAL_DESTROYER = 1305;

export const GROUP_T1_CRUISER = 26;
export const GROUP_SHIP_HAC = 358;
export const GROUP_SHIP_HIC = 894;
export const GROUP_COMBAT_RECON = 906;
export const GROUP_FORCE_RECON = 833;
export const GROUP_LOGISTICS_CRUISER = 832;
export const GROUP_STRATEGIC_CRUISER = 963;

export const GROUP_T1_COMBAT_BATTLECRUISER = 419;
export const GROUP_COMMAND_SHIP = 540;

export const GROUP_T1_ATTACK_BATTLECRUISER = 1201;

export const GROUP_T1_BATTLESHIP = 27;
export const GROUP_BLACK_OPS = 898;
export const GROUP_MARAUDER = 900;

export const GROUP_T1_INDUSTRIAL = 28;
export const GROUP_DST = 380;
export const GROUP_BLOCKADE_RUNNER = 1202;

export const GROUP_MOBILE_DEPOT = 1246;
export const GROUP_MOBILE_TRACTOR_UNIT = 1250;
export const GROUP_MOBILE_CYNOSURAL_BEACON = 4093;
export const GROUP_MOBILE_OBSERVATORY = 4107;
export const GROUP_MOBILE_WARP_DISRUPTOR = 361;

export const GROUP_SUPPORT_FIGHTER = 1537;
export const GROUP_LIGHT_FIGHTER = 1652;
export const GROUP_HEAVY_FIGHTER = 1653;

export const GROUP_SHUTTLE = 31;
