
export const MKT_GROUP_T1_FRIGATES_AMARR = 72;
export const MKT_GROUP_T1_FRIGATES_CALDARI = 61;
export const MKT_GROUP_T1_FRIGATES_GALLENTE = 77;
export const MKT_GROUP_T1_FRIGATES_MINMATAR = 64;

export const MKT_GROUPS_T1_FRIGATES = [
  MKT_GROUP_T1_FRIGATES_AMARR,
  MKT_GROUP_T1_FRIGATES_CALDARI,
  MKT_GROUP_T1_FRIGATES_GALLENTE,
  MKT_GROUP_T1_FRIGATES_MINMATAR
];

export const MKT_GROUP_T1_DESTROYERS_AMARR = 465;
export const MKT_GROUP_T1_DESTROYERS_CALDARI = 466;
export const MKT_GROUP_T1_DESTROYERS_GALLENTE = 467;
export const MKT_GROUP_T1_DESTROYERS_MINMATAR = 468;

export const MKT_GROUPS_T1_DESTROYERS = [
  MKT_GROUP_T1_DESTROYERS_AMARR,
  MKT_GROUP_T1_DESTROYERS_CALDARI,
  MKT_GROUP_T1_DESTROYERS_GALLENTE,
  MKT_GROUP_T1_DESTROYERS_MINMATAR
];

export const MKT_GROUP_T1_CRUISERS_AMARR = 74;
export const MKT_GROUP_T1_CRUISERS_CALDARI = 75;
export const MKT_GROUP_T1_CRUISERS_GALLENTE = 76;
export const MKT_GROUP_T1_CRUISERS_MINMATAR = 73;

export const MKT_GROUPS_T1_CRUISERS = [
  MKT_GROUP_T1_CRUISERS_AMARR,
  MKT_GROUP_T1_CRUISERS_CALDARI,
  MKT_GROUP_T1_CRUISERS_GALLENTE,
  MKT_GROUP_T1_CRUISERS_MINMATAR
];

export const MKT_GROUP_NAVY_FRIGATES = 1366;
export const MKT_GROUP_NAVY_CRUISERS = 1370;
export const MKT_GROUP_NAVY_BATTLECRUISERS = 1704;
export const MKT_GROUP_NAVY_BATTLESHIPS = 1379;

export const MKT_GROUP_PIRATE_FRIGATES = 1365;
export const MKT_GROUP_PIRATE_CRUISERS = 1371;
export const MKT_GROUP_PIRATE_BATTLESHIPS = 1380;
