
export const TYPE_CAPSULE = 670;
export const TYPE_CAPSULE_GENOLUTION = 33328;

export const TYPE_GUARDIAN = 11987;

export const TYPE_TENGU = 29984;
export const TYPE_LEGION = 29986;
export const TYPE_LOKI = 29990;

export const TYPE_GNOSIS = 3756;
export const TYPE_DAMNATION = 22474;
export const TYPE_VULTURE = 22446;

export const TYPE_SCORPION = 640;
export const TYPE_BHAALGORN = 17920;

export const TYPE_LOW_GRADE_GRAIL_ALPHA = 32101;
export const TYPE_LOW_GRADE_GRAIL_BETA = 32102;
export const TYPE_LOW_GRADE_GRAIL_DELTA = 32103;
export const TYPE_LOW_GRADE_GRAIL_EPSILON = 32104;
export const TYPE_LOW_GRADE_GRAIL_GAMMA = 32105;
export const TYPE_LOW_GRADE_GRAIL_OMEGA = 32122;
export const TYPE_LOW_GRADE_GRAILS = [
  TYPE_LOW_GRADE_GRAIL_ALPHA,
  TYPE_LOW_GRADE_GRAIL_BETA,
  TYPE_LOW_GRADE_GRAIL_DELTA,
  TYPE_LOW_GRADE_GRAIL_EPSILON,
  TYPE_LOW_GRADE_GRAIL_GAMMA,
  TYPE_LOW_GRADE_GRAIL_OMEGA,
];

export const TYPE_HIGH_GRADE_GRAIL_ALPHA = 31954;
export const TYPE_HIGH_GRADE_GRAIL_BETA = 31955;
export const TYPE_HIGH_GRADE_GRAIL_DELTA = 31956;
export const TYPE_HIGH_GRADE_GRAIL_EPSILON = 31957;
export const TYPE_HIGH_GRADE_GRAIL_GAMMA = 31958;
export const TYPE_HIGH_GRADE_GRAIL_OMEGA = 31959;
export const TYPE_HIGH_GRADE_GRAILS = [
  TYPE_HIGH_GRADE_GRAIL_ALPHA,
  TYPE_HIGH_GRADE_GRAIL_BETA,
  TYPE_HIGH_GRADE_GRAIL_DELTA,
  TYPE_HIGH_GRADE_GRAIL_EPSILON,
  TYPE_HIGH_GRADE_GRAIL_GAMMA,
  TYPE_HIGH_GRADE_GRAIL_OMEGA,
];

export const TYPE_LOW_GRADE_TALON_ALPHA = 32112;
export const TYPE_LOW_GRADE_TALON_BETA = 32113;
export const TYPE_LOW_GRADE_TALON_DELTA = 32114;
export const TYPE_LOW_GRADE_TALON_EPSILON = 32115;
export const TYPE_LOW_GRADE_TALON_GAMMA = 32116;
export const TYPE_LOW_GRADE_TALON_OMEGA = 32125;
export const TYPE_LOW_GRADE_TALONS = [
  TYPE_LOW_GRADE_TALON_ALPHA,
  TYPE_LOW_GRADE_TALON_BETA,
  TYPE_LOW_GRADE_TALON_DELTA,
  TYPE_LOW_GRADE_TALON_EPSILON,
  TYPE_LOW_GRADE_TALON_GAMMA,
  TYPE_LOW_GRADE_TALON_OMEGA,
];

export const TYPE_HIGH_GRADE_TALON_ALPHA = 31962;
export const TYPE_HIGH_GRADE_TALON_BETA = 31963;
export const TYPE_HIGH_GRADE_TALON_DELTA = 31964;
export const TYPE_HIGH_GRADE_TALON_EPSILON = 31965;
export const TYPE_HIGH_GRADE_TALON_GAMMA = 31966;
export const TYPE_HIGH_GRADE_TALON_OMEGA = 31967;
export const TYPE_HIGH_GRADE_TALONS = [
  TYPE_HIGH_GRADE_TALON_ALPHA,
  TYPE_HIGH_GRADE_TALON_BETA,
  TYPE_HIGH_GRADE_TALON_DELTA,
  TYPE_HIGH_GRADE_TALON_EPSILON,
  TYPE_HIGH_GRADE_TALON_GAMMA,
  TYPE_HIGH_GRADE_TALON_OMEGA,
];

export const TYPE_HIGH_GRADE_TALISMAN_ALPHA = 19534;
export const TYPE_HIGH_GRADE_TALISMAN_BETA = 19535;
export const TYPE_HIGH_GRADE_TALISMAN_DELTA = 19536;
export const TYPE_HIGH_GRADE_TALISMAN_EPSILON = 19537;
export const TYPE_HIGH_GRADE_TALISMAN_GAMMA = 19538;
export const TYPE_HIGH_GRADE_TALISMAN_OMEGA = 19539;
export const TYPE_HIGH_GRADE_TALISMANS = [
  TYPE_HIGH_GRADE_TALISMAN_ALPHA,
  TYPE_HIGH_GRADE_TALISMAN_BETA,
  TYPE_HIGH_GRADE_TALISMAN_DELTA,
  TYPE_HIGH_GRADE_TALISMAN_EPSILON,
  TYPE_HIGH_GRADE_TALISMAN_GAMMA,
  TYPE_HIGH_GRADE_TALISMAN_OMEGA,
];

export const TYPE_MID_GRADE_TALISMAN_ALPHA = 22131;
export const TYPE_MID_GRADE_TALISMAN_BETA = 22133;
export const TYPE_MID_GRADE_TALISMAN_DELTA = 22134;
export const TYPE_MID_GRADE_TALISMAN_EPSILON = 22135;
export const TYPE_MID_GRADE_TALISMAN_GAMMA = 22136;
export const TYPE_MID_GRADE_TALISMAN_OMEGA = 22137;
export const TYPE_MID_GRADE_TALISMANS = [
  TYPE_MID_GRADE_TALISMAN_ALPHA,
  TYPE_MID_GRADE_TALISMAN_BETA,
  TYPE_MID_GRADE_TALISMAN_DELTA,
  TYPE_MID_GRADE_TALISMAN_EPSILON,
  TYPE_MID_GRADE_TALISMAN_GAMMA,
  TYPE_MID_GRADE_TALISMAN_OMEGA,
];

export const TYPE_LOW_GRADE_TALISMAN_ALPHA = 33965;
export const TYPE_LOW_GRADE_TALISMAN_BETA = 333966;
export const TYPE_LOW_GRADE_TALISMAN_DELTA = 333967;
export const TYPE_LOW_GRADE_TALISMAN_EPSILON = 333968;
export const TYPE_LOW_GRADE_TALISMAN_GAMMA = 333969;
export const TYPE_LOW_GRADE_TALISMAN_OMEGA = 333970;
export const TYPE_LOW_GRADE_TALISMANS = [
  TYPE_LOW_GRADE_TALISMAN_ALPHA,
  TYPE_LOW_GRADE_TALISMAN_BETA,
  TYPE_LOW_GRADE_TALISMAN_DELTA,
  TYPE_LOW_GRADE_TALISMAN_EPSILON,
  TYPE_LOW_GRADE_TALISMAN_GAMMA,
  TYPE_LOW_GRADE_TALISMAN_OMEGA,
];

export const TYPE_ARMORED_COMMAND_MINDLINK = 13209;
export const TYPE_SHIELD_COMMAND_MINDLINK = 21888;
export const TYPE_INFORMATION_COMMAND_MINDLINK = 21889;
export const TYPE_SKIRMISH_COMMAND_MINDLINK = 21890;

export const TYPE_IMPERIAL_NAVY_MINDLINK = 33403;
export const TYPE_FEDERATION_NAVY_MINDLINK = 33404;
export const TYPE_REPUBLIC_FLEET_MINDLINK = 33405;
export const TYPE_CALDARI_NAVY_MINDLINK = 33406;
