export enum EsiScope {
  OPEN_WINDOW = "esi-ui.open_window.v1",
  CORP_READ_KILLMAILS = "esi-killmails.read_corporation_killmails.v1",
  CORP_READ_MEMBERSHIP = "esi-corporations.read_corporation_membership.v1",
  CORP_READ_TITLES = "esi-corporations.read_titles.v1",
  CORP_TRACK_MEMBERS = "esi-corporations.track_members.v1",
  READ_ASSETS = "esi-assets.read_assets.v1",
  READ_LOCATION = "esi-location.read_location.v1",
  READ_NOTIFICATIONS = "esi-characters.read_notifications.v1",
  READ_ONLINE = "esi-location.read_online.v1",
  READ_ROLES = "esi-characters.read_corporation_roles.v1",
  READ_SHIP_TYPE = "esi-location.read_ship_type.v1",
  READ_SKILLS = "esi-skills.read_skills.v1",
  READ_SKILLQUEUE = "esi-skills.read_skillqueue.v1",
}
